name: Download Artifact and Post Comment

on:
  workflow_run:
    workflows: ["Python CI"]
    types:
      - completed
  pull_request_target:
    types:
      - opened
      - synchronize


jobs:
  download_artifact_and_post_comment:
    if: ${{ github.event_name == 'workflow_run' || (github.event_name == 'pull_request_target' && github.event.action == 'synchronize') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
