name: Download Artifact and Post Comment

on:
  workflow_run:
    workflows: ["first_workflow"]
    types:
      - completed
  pull_request_target:
    types:
      - opened
      - synchronize


jobs:
  download_artifact_and_post_comment:
    if: ${{ github.event_name == 'workflow_run' || (github.event_name == 'pull_request_target' && github.event.action == 'synchronize') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download xfail_reasons_log artifact
        continue-on-error: true
        uses: actions/download-artifact@v2
        with:
          name: xfail_reasons_log

      - name: Check if artifact contains "benchmark"
        id: check_content
        continue-on-error: true
        run: |
          if grep -q "benchmark" xfail_reasons.log; then
            echo "Found benchmark"
            echo "::set-output name=contains_benchmark::true"
          else
            echo "Benchmark not found"
            echo "::set-output name=contains_benchmark::false"
          fi

      - name: Post comment if benchmark found
        if: steps.check_content.outputs.contains_benchmark == 'true'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.payload.pull_request.number;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: "test",
            });
